import { assertSlugs } from "@/lib/slug";

export type City = {
  seoNote: string; // SEO-specific local context
  creatorNote: string; // influencer-marketing local context
  slug: string;
  name: string;
  state: string;
  areas: string[]; // real localities — gives each city page unique, useful content
  note: string; // hand-written local context
};

/**
 * Only cities with hand-written local context live here. Do NOT bulk-generate city pages
 * from a list of names — doorway/thin pages hurt the whole domain. Add a city only with real notes.
 */
export const cities: City[] = [
  { slug: "mumbai", seoNote: "Mumbai is among India's most competitive search markets, with finance, real estate and D2C brands chasing the same head terms. Winning usually means owning specific suburb- and intent-led pages rather than broad keywords.", creatorNote: "Mumbai has India's deepest pool of fashion, food and entertainment creators, with audiences spread across the western and central suburbs. It suits launches, restaurant openings and event promotion.", name: "Mumbai", state: "Maharashtra", areas: ["Andheri", "Bandra", "Powai", "Thane"], note: "Mumbai searches are intensely hyperlocal — people look for a clinic, salon or restaurant 'near me' within a few kilometres along the suburban rail corridors, so each branch needs its own accurate pin, hours and reviews." },
  { slug: "delhi", seoNote: 'Delhi searches span the NCR, so brands compete across Delhi, Noida and Gurugram at once. Clear location structure and strong local signals stop pages from cannibalising each other.', creatorNote: "Delhi's creator scene covers fashion, street food, travel and politics-adjacent commentary, and audiences skew across the wider NCR. City-matched creators help brands with several outlets.", name: "Delhi", state: "Delhi", areas: ["Connaught Place", "Saket", "Lajpat Nagar", "Dwarka"], note: "Delhi has dense market clusters where dozens of near-identical businesses compete for the same map pack, so photos, review velocity and category accuracy decide who is shown first." },
  { slug: "bengaluru", seoNote: "Bengaluru's tech-savvy audience researches heavily before buying, and many SaaS and startup brands compete here. Detailed, expert content and strong technical foundations pay off.", creatorNote: 'Bengaluru is home to many tech, fitness, food and lifestyle creators with highly digital audiences, a good fit for app launches, gadgets and cafe and restaurant campaigns.', name: "Bengaluru", state: "Karnataka", areas: ["Koramangala", "Indiranagar", "Whitefield", "HSR Layout"], note: "Bengaluru's spread-out tech corridors mean demand is split by neighbourhood; multi-outlet brands win by managing every outlet's profile and review replies centrally." },
  { slug: "hyderabad", seoNote: "Hyderabad's growth around Hitech City and Gachibowli has created new commercial and residential demand, with plenty of real estate and IT-services brands competing for visibility.", creatorNote: 'Hyderabad has a strong food culture and a large regional-language audience, so creators who post in Telugu and English help brands reach the city authentically.', name: "Hyderabad", state: "Telangana", areas: ["Hitech City", "Banjara Hills", "Gachibowli", "Secunderabad"], note: "Hyderabad's growth around Hitech City and Gachibowli created new commercial pockets where newly opened outlets need fast verification and review momentum." },
  { slug: "chennai", seoNote: 'Chennai users search in both English and Tamil, so bilingual content can capture queries competitors miss, especially for local services, education and healthcare.', creatorNote: 'Chennai creators often work in Tamil and English, and local-language content tends to build trust quickly for food, fashion, education and retail brands.', name: "Chennai", state: "Tamil Nadu", areas: ["T. Nagar", "Adyar", "Anna Nagar", "Velachery"], note: "Chennai customers frequently search in English and Tamil, so profiles with bilingual descriptions and accurate service lists capture more local queries." },
  { slug: "pune", seoNote: "Pune's student and IT-professional population searches heavily for courses, rentals, gyms and cafes, and a growing real estate market adds competition for location-led queries.", creatorNote: "Pune's youthful, student-heavy audience responds well to cafes, fitness, education and lifestyle campaigns run with local creators.", name: "Pune", state: "Maharashtra", areas: ["Kothrud", "Hinjewadi", "Viman Nagar", "Koregaon Park"], note: "Pune's student and IT-professional population searches heavily for cafes, gyms, coaching and rentals, which makes fresh photos and up-to-date hours critical." },
  { slug: "kolkata", seoNote: 'Kolkata combines established businesses with a growing digital audience. Many competitors still under-invest in SEO, so well-structured local and content pages can stand out.', creatorNote: 'Kolkata creators have strong communities around food, culture, fashion and festivals such as Durga Puja, which makes seasonal campaigns especially effective.', name: "Kolkata", state: "West Bengal", areas: ["Salt Lake", "Park Street", "New Town", "Howrah"], note: "Kolkata's mix of old market streets and new townships makes address and landmark accuracy essential — wrong pins are the most common reason customers never arrive." },
  { slug: "ahmedabad", seoNote: "Ahmedabad's strong business community and growing e-commerce and manufacturing sectors make it a good market for lead-generation SEO built around commercial and B2B queries.", creatorNote: 'Ahmedabad creators have engaged audiences around food, fashion and festivals like Navratri, giving brands natural seasonal moments to work with.', name: "Ahmedabad", state: "Gujarat", areas: ["SG Highway", "Navrangpura", "Satellite", "Maninagar"], note: "Ahmedabad's SG Highway corridor concentrates showrooms, restaurants and clinics, so standing out in the map pack there depends on reviews and consistent posting." },
  { slug: "jaipur", seoNote: "Jaipur's tourism, handicrafts and wedding economy creates strong seasonal search demand. Pages that target travel, jewellery and wedding services should be planned ahead of peak months.", creatorNote: "Jaipur's travel, heritage and wedding content is popular nationally, so local creators suit hospitality, jewellery, fashion and destination campaigns.", name: "Jaipur", state: "Rajasthan", areas: ["C-Scheme", "Malviya Nagar", "Vaishali Nagar", "Mansarovar"], note: "Jaipur's tourism and wedding economy means seasonal spikes in 'near me' searches; scheduling posts and offers ahead of peak months keeps profiles active." },
  { slug: "gurugram", seoNote: "Gurugram's corporate and real estate market is crowded, so SEO here often focuses on B2B services, premium residential projects and professional services with long consideration cycles.", creatorNote: 'Gurugram creators lean towards lifestyle, fitness, food and corporate-professional content, reaching an affluent, urban audience.', name: "Gurugram", state: "Haryana", areas: ["DLF Phase 3", "Golf Course Road", "Sohna Road", "Sector 29"], note: "Gurugram's office-driven demand peaks at lunch and after work, so accurate opening hours and special-hours updates directly affect footfall." },
  { slug: "chandigarh", seoNote: "Chandigarh's tricolity spread across Mohali and Panchkula means searches mix sector, city and neighbouring-town terms. Pages that cover those variations carefully capture more demand.", creatorNote: 'Chandigarh and the wider Punjab audience respond strongly to music, food, fashion and wedding content, with many creators working in Punjabi and Hindi.', name: "Chandigarh", state: "Chandigarh", areas: ["Sector 17", "Sector 35", "Mohali", "Panchkula"], note: "Chandigarh's sector-based addresses confuse customers and maps alike; profiles that include clear landmarks and sector references get fewer wrong-turn visits." },
  { slug: "lucknow", seoNote: "Lucknow's healthcare, education and food sectors are strongly search-driven, and many local businesses still have thin websites, which leaves room for well-built pages to rank.", creatorNote: 'Lucknow creators have loyal audiences around food, fashion and culture, and content in Hindi and Urdu-influenced language builds trust for local brands.', name: "Lucknow", state: "Uttar Pradesh", areas: ["Gomti Nagar", "Hazratganj", "Aliganj", "Indira Nagar"], note: "Lucknow's food and healthcare searches are strongly review-driven; replying to every review in the customer's own language builds trust quickly." },
];

assertSlugs("city", cities.map((c) => c.slug));
export const getCity = (slug: string) => cities.find((c) => c.slug === slug);
